from enum import IntEnum


class OpGroup(IntEnum):
    L2CAP = 0x42
    GATT = 0x45
    GATT_DB = 0x46
    BLE = 0x47
    GAP = 0x48
    FSCI_request = 0xA3
    FSCI_response = 0xA4


class OpCodeFSCI(IntEnum):
    ALLOW_DEVICE_TO_SLEEP = 0x70
    ERROR = 0xFE
    GET_WAKEUP_REASON = 0x72
    WAKEUP = 0x71


class OpCodeGATTDB(IntEnum):
    CONFIRM = 0x80
    ADD_CCCD_REQ = 0x0F
    ADD_CCCD_IND = 0x8F
    ADD_CHARACTERISTIC_DECLARATION_AND_VALUE_REQ = 0x0D
    ADD_CHARACTERISTIC_DECLARATION_AND_VALUE_IND = 0x89
    ADD_CHARACTERISTIC_DECLARATION_WITH_UNIQUE_VALUE_REQ = 0x10
    ADD_CHARACTERISTIC_DECLARATION_WITH_UNIQUE_VALUE_IND = 0x8C
    ADD_CHARACTERISTIC_DESCRIPTOR_REQ = 0x0E
    ADD_CHARACTERISTIC_DESCRIPTOR_IND = 0x8A
    ADD_INCLUDE_DECLARATION_REQ = 0x0C
    ADD_INCLUDE_DECLARATION_IND = 0x88
    ADD_PRIMARY_SERVICE_DECLARATION_REQ = 0x0A
    ADD_PRIMARY_SERVICE_DECLARATION_IND = 0x86
    ADD_SECONDARY_SERVICE_DECLARATION_REQ = 0x0B
    ADD_SECONDARY_SERVICE_DECLARATION_IND = 0x87
    DYN_INIT = 0x08
    RELEASE_DATABASE = 0x09
    REMOVE_CHARACTERISTIC = 0x12
    REMOVE_SERVICE = 0x11


class OpCodeGAP(IntEnum):
    HOST_INITIALIZE = 0x01
    CONFIRM = 0x80
    ACCEPT_PAIRING_REQUEST = 0x0F
    ADD_DEVICE_TO_WHITELIST = 0x23
    ADVERTISING_EVENT_COMMAND_FAILED = 0x99
    ADVERTISING_EVENT_STATE_CHANGED = 0x98
    AUTHORIZE = 0x07
    CHECK_IF_BONDED_REQ = 0x20
    CHECK_IF_BONDED_IND = 0x86
    CHECK_INDICATION_STATUS_REQ = 0x0A
    CHECK_INDICATION_STATUS_IND = 0x82
    CHECK_NOTIFICATION_STATUS_REQ = 0x09
    CHECK_NOTIFICATION_STATUS_IND = 0x81
    CLEAR_WHITELIST = 0x22
    CONNECT = 0x1C
    CONNECTION_EVENT_AUTHENTICATION_REJECTED = 0xA1
    CONNECTION_EVENT_CONNECTED = 0x9D
    CONNECTION_EVENT_DISCONNECTED = 0xAA
    CONNECTION_EVENT_ENCRYPTION_CHANGED = 0xA8
    CONNECTION_EVENT_KEY_EXCHANGE_REQUEST = 0xA5
    CONNECTION_EVENT_KEYS_RECEIVED = 0xA6
    CONNECTION_EVENT_LE_DATA_LENGTH_CHANGED = 0xB0
    CONNECTION_EVENT_LE_SC_DISPLAY_NUMERIC_VALUE = 0xB2
    CONNECTION_EVENT_LE_SC_KEYPRESS_NOTIFICATION = 0xB3
    CONNECTION_EVENT_LE_SC_OOB_DATA_REQUEST = 0xB1
    CONNECTION_EVENT_LONG_TERM_KEY_REQUEST = 0xA7
    CONNECTION_EVENT_OOB_REQUEST = 0xA3
    CONNECTION_EVENT_PAIRING_COMPLETE = 0xA9
    CONNECTION_EVENT_PAIRING_REQUEST = 0x9E
    CONNECTION_EVENT_PAIRING_RESPONSE = 0xA0
    CONNECTION_EVENT_PARAMETER_UPDATE_COMPLETE = 0xAF
    CONNECTION_EVENT_PARAMETER_UPDATE_REQUEST = 0xAE
    GENERIC_EVENT_ADVERTISING_DATA_SETUP_COMPLETE = 0x8D
    GENERIC_EVENT_ADVERTISING_PARAMETERS_SETUP_COMPLETE = 0x8C
    GENERIC_EVENT_ADVERTISING_SETUP_FAILED = 0x8B
    GENERIC_EVENT_ADV_TX_POWER_LEVEL_READ = 0x95
    GENERIC_EVENT_CONTROLLER_PRIVACY_STATE_CHANGED = 0xB7
    GENERIC_EVENT_CONTROLLER_RESET_COMPLETE = 0xB4
    GENERIC_EVENT_CREATE_CONNECTION_CANCELED = 0x93
    GENERIC_EVENT_DEVICE_ADDED_TO_WHITELIST = 0x8F
    GENERIC_EVENT_DEVICE_REMOVED_FROM_WHITELIST = 0x8F
    GENERIC_EVENT_INITIALIZATION_COMPLETE = 0x89
    GENERIC_EVENT_INTERNAL_ERROR = 0x8A
    GENERIC_EVENT_LE_SC_LOCAL_OOB_DATA = 0xB6
    GENERIC_EVENT_PRIVATE_RESOLVABLE_ADDRESS_VERIFIED = 0x96
    GENERIC_EVENT_PUBLIC_ADDRESS_READY = 0x94
    GENERIC_EVENT_RANDOM_ADDRESS_READY = 0x92
    GENERIC_EVENT_RANDOM_ADDRESS_SET = 0x97
    GENERIC_EVENT_TX_POWER_LEVEL_SET_COMPLETE = 0xB9
    GENERIC_EVENT_WHITELIST_CLEARED = 0x91
    GENERIC_EVENT_WHITELIST_SIZE_READ = 0x8E
    READ_PUBLIC_DEVICE_ADDRESS = 0x25
    SCANNING_EVENT_STATE_CHANGED = 0x9A
    SCANNING_EVENT_COMMAND_FAILED = 0x9B
    SCANNING_EVENT_DEVICE_SCANNED = 0x9C
    SET_ADVERTISING_DATA = 0x04
    SET_ADVERTISING_PARAMETERS = 0x03
    SET_TX_POWER_LEVEL = 0x3D
    START_ADVERTISING = 0x05
    START_SCANNING = 0x1A
    STOP_ADVERTISING = 0x06
    STOP_SCANNING = 0x1B


class OpCodeGATT(IntEnum):
    CONFIRM = 0x80
    DISCOVER_ALL_CHARACTERISTIC_DESCRIPTORS = 0x0E
    DISCOVER_ALL_CHARACTERISTIC_OF_SERVICE = 0x0C
    DISCOVER_ALL_PRIMARY_SERVICES = 0x09
    DISCOVER_CHARACTERISTIC_OF_SERVICE_BY_UUID = 0x0D
    DISCOVER_PRIMARY_SERVICES_BY_UUID = 0x0A
    EXCHANGE_MTU = 0x08
    FIND_INCLUDED_SERVICES = 0x0B
    INDICATION = 0x90
    CLIENT_INIT = 0x03
    CLIENT_NOTIFICATION = 0x8F
    PROCEDURE_DISCOVER_ALL_CHARACTERISTIC_DESCRIPTORS = 0x88
    PROCEDURE_DISCOVER_ALL_CHARACTERISTICS = 0x86
    PROCEDURE_DISCOVER_ALL_PRIMARY_SERVICES = 0x83
    PROCEDURE_DISCOVER_CHARACTERISTIC_BY_UUID = 0x83
    PROCEDURE_DISCOVER_PRIMARY_SERVICES_BY_UUID = 0x84
    PROCEDURE_EXCHANGE_MTU = 0x85
    PROCEDURE_FIND_INCLUDED_SERVICES = 0x85
    PROCEDURE_READ_CHARACTERISTIC_DESCRIPTOR = 0x8D
    PROCEDURE_READ_CHARACTERISTIC_VALUE = 0x89
    PROCEDURE_READ_MULTIPLE_CHARACTERISTIC_VALUES = 0x8B
    PROCEDURE_READ_USING_CHARACTERISTIC_UUID = 0x8A
    PROCEDURE_WRITE_CHARACTERISTIC_DESCRIPTOR = 0x8E
    PROCEDURE_WRITE_CHARACTERISTIC_VALUE = 0x8C
    READ_CHARACTERISTIC_VALUE = 0x0F
    REGISTER_NOTIFICATION_CALLBACK = 0x06
    REGISTER_PROCEDURE_CALLBACK = 0x05
    WRITE_CHARACTERISTIC_VALUE = 0x12
